name: CI
on:
  push:

permissions:
  contents: read

env:
  PRIMARY_NODE_V: '20.x'

jobs:
  build:
    name: Build on Node '${{ matrix.node }}'

    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ['18.x', '20.x']

    steps:
      - name: Checkout '${{ github.ref_name }}' branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref_name }}

      - name: Use Node '${{ matrix.node }}'
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: 'npm' # The action has a built-in functionality for caching and restoring dependencies. https://github.com/actions/setup-node/#caching-global-packages-data

      - name: Install deps
        run: npm ci

      - name: Build
        run: npm run build

      # - name: Format Check & Test
      #   continue-on-error: true
      #   run: npm run test

  lint-commit:
    name: Lint commit messages
    runs-on: ubuntu-latest
    if: github.ref_name != 'main'
    steps:
      - name: Checkout '${{ github.ref_name }}' branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref_name }}
          sparse-checkout: .

      - name: Use Node '${{ env.PRIMARY_NODE_V }}'
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.PRIMARY_NODE_V }}
          cache: 'npm' # The action has a built-in functionality for caching and restoring dependencies. https://github.com/actions/setup-node/#caching-global-packages-data
